// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: entry.sql

package db

import (
	"context"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
  akun_id, 
  amount
) VALUES (
  $1, $2
) RETURNING id, akun_id, amount, created_at
`

type CreateEntryParams struct {
	AkunID int64 `json:"akun_id"`
	Amount int64 `json:"amount"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry, arg.AkunID, arg.Amount)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AkunID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, akun_id, amount, created_at FROM entries
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEntry(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AkunID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
