// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	AddAkunBalance(ctx context.Context, arg AddAkunBalanceParams) (Akun, error)
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Akun, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfers(ctx context.Context, arg CreateTransfersParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAkun(ctx context.Context, id int64) error
	GetAkunForUpdate(ctx context.Context, id int64) (Akun, error)
	GetAuthor(ctx context.Context, id int64) (Akun, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAuthors(ctx context.Context, arg ListAuthorsParams) ([]Akun, error)
	UpdateAkun(ctx context.Context, arg UpdateAkunParams) (Akun, error)
}

var _ Querier = (*Queries)(nil)
